# Generated by Django 3.0.6 on 2020-05-17 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0004_auto_20200517_0305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='school',
            options={},
        ),
    ]
