# Generated by Django 3.0.6 on 2020-05-17 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0005_auto_20200517_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='datas.School'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='school',
            table=None,
        ),
    ]
