# Generated by Django 3.0.6 on 2020-05-17 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0006_auto_20200517_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='datas.School'),
        ),
    ]
