# Generated by Django 3.0.6 on 2020-05-17 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0007_auto_20200517_0408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='school_id',
            new_name='school',
        ),
    ]
