# Generated by Django 3.0.6 on 2020-06-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0008_auto_20200517_0450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('train_plan', models.CharField(blank=True, max_length=255, null=True)),
                ('plan_time', models.DateTimeField(blank=True, null=True)),
                ('materials', models.CharField(blank=True, max_length=255, null=True)),
                ('personnel', models.CharField(blank=True, max_length=255, null=True)),
                ('propaganda', models.CharField(blank=True, max_length=255, null=True)),
                ('feedback', models.CharField(blank=True, max_length=255, null=True)),
                ('sign_in', models.CharField(blank=True, max_length=255, null=True)),
                ('serve_people', models.IntegerField(blank=True, null=True)),
                ('scenes', models.IntegerField(blank=True, null=True)),
                ('form', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'activity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('numbering', models.CharField(blank=True, max_length=255, null=True)),
                ('attrition_rate', models.CharField(blank=True, max_length=255, null=True)),
                ('rotation_times', models.CharField(blank=True, max_length=255, null=True)),
                ('use_record', models.CharField(blank=True, max_length=255, null=True)),
                ('rotation_record', models.CharField(blank=True, max_length=255, null=True)),
                ('feedback', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('flow_in', models.CharField(blank=True, max_length=255, null=True)),
                ('flow_out', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChildrenResearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_number', models.IntegerField(blank=True, null=True)),
                ('form', models.CharField(blank=True, max_length=255, null=True)),
                ('plan', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'children_research',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.CharField(blank=True, max_length=255, null=True)),
                ('class_field', models.CharField(blank=True, db_column='class', max_length=255, null=True)),
                ('student_number', models.IntegerField(blank=True, null=True)),
                ('book_corner', models.CharField(blank=True, max_length=255, null=True)),
                ('book_number', models.IntegerField(blank=True, null=True)),
                ('use_frequency', models.CharField(blank=True, max_length=255, null=True)),
                ('corner_image', models.CharField(blank=True, max_length=255, null=True)),
                ('book_flow_round', models.CharField(blank=True, max_length=255, null=True)),
                ('morning_read', models.CharField(blank=True, max_length=255, null=True)),
                ('reading_frequency', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_time', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_frequency', models.CharField(blank=True, max_length=255, null=True)),
                ('lesson_time', models.CharField(blank=True, max_length=255, null=True)),
                ('lesson_frequency', models.CharField(blank=True, max_length=255, null=True)),
                ('jon_survey_number', models.IntegerField(blank=True, null=True)),
                ('charger', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coorperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('resources', models.CharField(blank=True, max_length=255, null=True)),
                ('willing', models.CharField(blank=True, max_length=255, null=True)),
                ('needs', models.CharField(blank=True, max_length=255, null=True)),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('project_cycle', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'coorperation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('book_number', models.IntegerField(blank=True, null=True)),
                ('good_book_ratio', models.CharField(blank=True, max_length=255, null=True)),
                ('manager', models.CharField(blank=True, max_length=255, null=True)),
                ('open', models.CharField(blank=True, max_length=255, null=True)),
                ('record', models.CharField(blank=True, max_length=255, null=True)),
                ('electric', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'library',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('object', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Punch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('days', models.IntegerField(blank=True, null=True)),
                ('test_content', models.CharField(blank=True, max_length=255, null=True)),
                ('person_number', models.IntegerField(blank=True, null=True)),
                ('times', models.IntegerField(blank=True, null=True)),
                ('prize', models.CharField(blank=True, max_length=255, null=True)),
                ('winners', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'punch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Punch2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=255, null=True)),
                ('school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.CharField(blank=True, max_length=255, null=True)),
                ('class_field', models.CharField(blank=True, db_column='class', max_length=255, null=True)),
                ('punch_times', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'punch2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StaffEstimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('focus_co_school_focus_co_school_focus_co_school', models.CharField(blank=True, db_column='focus_co_school\r\nfocus_co_school\r\nfocus_co_school', max_length=255, null=True)),
                ('willing', models.CharField(blank=True, max_length=255, null=True)),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'staff_estimate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('serve_people', models.CharField(blank=True, max_length=255, null=True)),
                ('form', models.CharField(blank=True, max_length=255, null=True)),
                ('period', models.CharField(blank=True, max_length=255, null=True)),
                ('start_data', models.CharField(blank=True, max_length=255, null=True)),
                ('end_data', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'survey',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('personnel', models.CharField(blank=True, max_length=255, null=True)),
                ('serve_people', models.IntegerField(blank=True, null=True)),
                ('docking', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('need_follow', models.CharField(blank=True, max_length=255, null=True)),
                ('doc', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'visit',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
