# Generated by Django 3.0.6 on 2020-07-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildrenResearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_number', models.IntegerField(blank=True, null=True)),
                ('form', models.CharField(blank=True, max_length=255, null=True)),
                ('plan', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'children_research',
                'managed': False,
            },
        ),
    ]
